<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<!--
 - @author  Michal Mikoláš <nanuqcz@gmail.com>
 - @author  Jiri Petruzelka <petruzelka@nox-art.cz>
 - @license CC BY-SA <http://creativecommons.org/licenses/by-sa/3.0/>
 -->
<dict>  <!-- Latte syntax definition -->
	<key>fileTypes</key>
	<array>
		<string>phtml</string>
		<string>latte</string>
	</array>
	<key>name</key>
	<string>Latte</string>
	<key>scopeName</key>
	<string>source.latte</string>
	<key>patterns</key>
	<array>

		<dict>  <!-- Latte comments -->
			<key>begin</key>
			<string>\{\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.latte</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*\}</string>
			<key>name</key>
			<string>comment.block.latte</string>
			<key>patterns</key>
			<array>
				<dict>  <!-- Anotations -->
					<key>match</key>
					<string>\@(author|param|copyright|package|see|license)</string>
					<key>name</key>
					<string>keyword.other.phpdoc</string>
				</dict>
				<dict>  <!-- Latte variables -->
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
		<dict>  <!-- Whatever between { and } -->
			<key>begin</key>
			<string>\{\{?(?!\s)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.latte</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}?\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.latte</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.latte</string>
			<key>patterns</key>
			<array>

				<dict>  <!-- Unescaped -->
					<key>match</key>
					<string>(?&lt;=\{)(\![^}]*)</string>
					<key>name</key>
					<string>keyword.unescaped.latte</string>
				</dict>
				<dict>  <!-- Numbers -->
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>  <!-- Latte variables -->
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>  <!-- Pair latte macros -->
					<key>match</key>
					<string>(?&lt;=\{)/?(block|foreach|form|ifset|elseif|if|else|snippet|ifset|ifCurrent|for|foreach|while|first|last|sep|capture|cache|syntaxblock|syntax|define)\s*</string>
					<key>name</key>
					<string>keyword.control.latte</string>
				</dict>
				<dict>  <!-- Single latte macros -->
					<key>match</key>
					<string>(?&lt;=\{)(var|link|plink|control|\!|label|input|default|include|l|r|use|contentType|status|_|layout|extends|dump|debugbreak)\s*</string>
					<key>name</key>
					<string>keyword.operator.latte</string>
				</dict>
				<dict>  <!-- Operators -->
					<key>match</key>
					<string>\!|and|or|===|!==|&gt;=|&lt;=|&lt;&gt;|&gt;|&lt;|==|!=|true|false|\+|\-|\*|/|%</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<dict>  <!-- Deprecated keywords -->
					<key>match</key>
					<string>widget</string>
					<key>name</key>
					<string>invalid.deprecated</string>
				</dict>
				<dict>  <!-- Helpers -->
					<key>match</key>
					<string>.*?(\|)(\w+)(?:\:([^\|\}]+))*</string> <!-- @todo matches only last argument - why? -->
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.helper.separator.latte</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.helper.name.latte</string>
						</dict>
						<!--
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.helper.argument.latte</string>
						</dict>
						-->
					</dict>
				</dict>
				<dict>  <!-- Strings -->
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>  <!-- Whatever else between { and } -->
					<key>match</key>
					<string>[a-zA-Z]+|[^}]|\s</string>
					<key>name</key>
					<string>source.latte</string>
				</dict>
			</array>
		</dict>

		<dict>  <!-- Include HTML highlight -->
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>

	<!-- Repository -->
	<key>repository</key>
	<dict>
		<key>variables</key>  <!-- Latte variables -->
		<dict>
			<key>match</key>
			<string>\$\$?[a-zA-Z_0-9]+\s*</string>
			<key>name</key>
			<string>variable.other.global.latte</string>
		</dict>

		<key>numbers</key> <!-- Numbers -->
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.latte</string>
		</dict>

		<key>strings</key>  <!-- Strings -->
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.latte</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.latte</string>
				</dict>
			</array>
		</dict>
	</dict>

</dict>
</plist>