<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>neon</string>
	</array>
	<key>name</key>
	<string>Neon</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(#)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.number-sign.neon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)\@[a-zA-Z_-]+</string>
					<key>name</key>
					<string>keyword.other.phpdoc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=:|\s)\d+(?=\s|$)</string>
			<key>name</key>
			<string>constant.language.neon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=:|\s)(true|True|TRUE|yes|Yes|YES|on|On|ON|false|False|FALSE|no|No|NO|off|Off|OFF|null|Null|NULL)(\s*$)</string>
			<key>name</key>
			<string>constant.language.neon</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.other.neon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.neon</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([a-zA-Z._-]*)(:)(?=\s*\S+)</string>
			<key>name</key>
			<string>keyword.control.neon</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.neon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.neon</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([a-zA-Z._-]*)(:)</string>
			<key>name</key>
			<string>keyword.control.neon</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.neon</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(-)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(@\w+)</string>
			<key>name</key>
			<string>support.class.neon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(["'])</string>
			<key>end</key>
			<string>(\1)</string>
			<key>name</key>
			<string>string.quoted.double.neon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>variables</key>
		<dict>
			<key>match</key>
			<string>(%.*?%)</string>
			<key>name</key>
			<string>variable.parameter.neon</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.neon</string>
	<key>uuid</key>
	<string>dac5b712-3e47-4e5c-8ba9-710f64722991</string>
</dict>
</plist>
